//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLog.Targets.NetworkJSON.LoadTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLog.Targets.NetworkJSON.LoadTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Here is a message that should not have headers in its data portion.&quot;,&quot;logSequenceId&quot;:8,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:37.9866989-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;Instrumentation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-instrumentation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData0 {
            get {
                return ResourceManager.GetString("TestData0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Execution Complete&quot;,&quot;logSequenceId&quot;:9,&quot;logLevel&quot;:&quot;Error&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:40.0452941-06:00&quot;,&quot;severity&quot;:30,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;Instrumentation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-instrumentation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;File Error\n&quot;,&quot;practice&quot;:&quot;JamesEby&quot;,&quot;clinic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData1 {
            get {
                return ResourceManager.GetString("TestData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;File write operation to &apos;C:\\Users\\jeby\\AppData\\Local\\Temp\\lt4uvv43.2d1&apos; successful.&quot;,&quot;logSequenceId&quot;:19,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:42.5728527-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;ConfigValidation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-configvalidation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;ho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData10 {
            get {
                return ResourceManager.GetString("TestData10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;The Info Push stack is clean&quot;,&quot;logSequenceId&quot;:25,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:44.6879448-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;EunEby&quot;,&quot;userId&quot;:null,&quot;invoic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData11 {
            get {
                return ResourceManager.GetString("TestData11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;The Info Push stack is clean&quot;,&quot;logSequenceId&quot;:11,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:40.0962362-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;Instrumentation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-instrumentation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;JamesEby&quot;,&quot;clinic&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData12 {
            get {
                return ResourceManager.GetString("TestData12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;The Info Push stack is   clean&quot;,&quot;logSequenceId&quot;:16,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:42.2346967-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;EunEby&quot;,&quot;userId&quot;:null,&quot;invo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData13 {
            get {
                return ResourceManager.GetString("TestData13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Starting the app logging&quot;,&quot;logSequenceId&quot;:20,&quot;logLevel&quot;:&quot;Trace&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:42.5964205-06:00&quot;,&quot;severity&quot;:0,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:null,&quot;userId&quot;:null,&quot;invoiceNumber&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData14 {
            get {
                return ResourceManager.GetString("TestData14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Finish up the logging test&quot;,&quot;logSequenceId&quot;:24,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:44.6703891-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;First one --&gt; This is some data I want to tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData15 {
            get {
                return ResourceManager.GetString("TestData15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Starting the app logging&quot;,&quot;logSequenceId&quot;:14,&quot;logLevel&quot;:&quot;Trace&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:40.1930338-06:00&quot;,&quot;severity&quot;:0,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:null,&quot;userId&quot;:null,&quot;invoiceNumber&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData16 {
            get {
                return ResourceManager.GetString("TestData16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Practice was set&quot;,&quot;logSequenceId&quot;:21,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:42.6144681-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;EunEby&quot;,&quot;userId&quot;:null,&quot;invoiceNumber&quot;:&quot;44 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData17 {
            get {
                return ResourceManager.GetString("TestData17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Status of directory write operation check.&quot;,&quot;logSequenceId&quot;:18,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:42.5457901-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;ConfigValidation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-configvalidation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;File write operat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData2 {
            get {
                return ResourceManager.GetString("TestData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;General Error&quot;,&quot;logSequenceId&quot;:23,&quot;logLevel&quot;:&quot;Error&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:44.6538439-06:00&quot;,&quot;severity&quot;:30,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;EunEby&quot;,&quot;userId&quot;:null,&quot;invoiceNumber&quot;:&quot;4456 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData3 {
            get {
                return ResourceManager.GetString("TestData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Application Run Summary&quot;,&quot;logSequenceId&quot;:26,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:44.7145045-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;Instrumentation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-instrumentation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;-------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData4 {
            get {
                return ResourceManager.GetString("TestData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Testing Trace&quot;,&quot;logSequenceId&quot;:13,&quot;logLevel&quot;:&quot;Trace&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:40.1664462-06:00&quot;,&quot;severity&quot;:0,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:null,&quot;userId&quot;:null,&quot;invoiceNumber&quot;:null,&quot;pati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData5 {
            get {
                return ResourceManager.GetString("TestData5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Execution Complete&quot;,&quot;logSequenceId&quot;:1,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:35.1972515-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;Instrumentation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-instrumentation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;Some Extra Data I added as a part of Log Met [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData6 {
            get {
                return ResourceManager.GetString("TestData6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Gettting ready to log the error.&quot;,&quot;logSequenceId&quot;:22,&quot;logLevel&quot;:&quot;Trace&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:44.6262706-06:00&quot;,&quot;severity&quot;:0,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;EunEby&quot;,&quot;userId&quot;:null,&quot;in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData7 {
            get {
                return ResourceManager.GetString("TestData7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Finish up the logging test&quot;,&quot;logSequenceId&quot;:10,&quot;logLevel&quot;:&quot;Info&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:40.073174-06:00&quot;,&quot;severity&quot;:10,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;Instrumentation&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-instrumentation&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;Practice was set\r\nSecond Info Stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData8 {
            get {
                return ResourceManager.GetString("TestData8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;General Error&quot;,&quot;logSequenceId&quot;:12,&quot;logLevel&quot;:&quot;Error&quot;,&quot;clientTimestamp&quot;:&quot;2017-02-27T16:53:40.1293862-06:00&quot;,&quot;severity&quot;:30,&quot;applicationLoggingId&quot;:&quot;pv-testapp-pvlogging&quot;,&quot;messageType&quot;:&quot;LogMessage&quot;,&quot;applicationName&quot;:&quot;PV.Logging.Tests&quot;,&quot;applicationVersion&quot;:&quot;1.2.3.4&quot;,&quot;logger&quot;:&quot;pv-testapp-pvlogging-logmessage&quot;,&quot;loggerVersion&quot;:&quot;4.3.2.1&quot;,&quot;userName&quot;:&quot;PV\\jeby&quot;,&quot;processName&quot;:&quot;JetBrains.ReSharper.TaskRunner.CLR45.x64&quot;,&quot;hostName&quot;:&quot;pvbmprl0036&quot;,&quot;data&quot;:&quot;&quot;,&quot;practice&quot;:&quot;TEST&quot;,&quot;userId&quot;:null,&quot;invoiceNumber&quot;:null,&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData9 {
            get {
                return ResourceManager.GetString("TestData9", resourceCulture);
            }
        }
    }
}
